version: '3.7'

services:
  db_producer:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swvl



  producer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db_producer


  rabbitmq:
    container_name: my_rabbit
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672



networks:
  default:
    external:
      name: rabbitmq_network




